### ISSUE TITLE
2016 County level 

### ISSUE THREAD

**Issue by tsmo4** [MEDSL/county-returns#1]
There are some inconsistencies in the `totalvotes` column in Arizona for the [2016 President results](https://github.com/MEDSL/county-returns/blob/master/countypres_2000-2016.csv). Particulalry in the Graham, Greenlee, and Gila counties.

Candidate vote totals appear to match [SOS reporting](https://apps.azsos.gov/election/2016/General/Official%20Signed%20State%20Canvass.pdf), but totalvotes are over reported (using either ballots cast, or sum of candidate votes.)

**Comment by agadjanian** [comment]
Thanks for flagging this discrepancy @tsmo4. I've corrected this total vote vs. summed candidate vote mistmatch for those three counties (as well as for a similar case in another state-year).

**Comment by tsmo4** [comment]
@agadjanian as a heads up this seems to have created some NAs elsewhere in the `totalvotes` column. Example:

Current file
![image](https://user-images.githubusercontent.com/7517172/77962063-e6c58d00-72a8-11ea-8bca-6e3901af2e54.png)

Previous file
![image](https://user-images.githubusercontent.com/7517172/77962168-16749500-72a9-11ea-9f10-7f37fe5ae06e.png)

**Comment by agadjanian** [comment]
Thanks for letting me know about this problem too @tsmo4, sorry about all of these issues. Just fixed and updated the data file. There should be no more NA values in `totalvotes`.
